"""empty message

Revision ID: 04d7dab273f4
Revises: 40a47fc282bf
Create Date: 2018-06-25 16:12:35.706471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04d7dab273f4'
down_revision = '40a47fc282bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_info', sa.Column('lastest_aa_bb', sa.Integer(), nullable=True))
    op.drop_column('ip_info', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_info', sa.Column('test', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('ip_info', 'lastest_aa_bb')
    # ### end Alembic commands ###
