"""empty message

Revision ID: 1f463034105a
Revises: 
Create Date: 2018-06-25 16:02:59.727074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f463034105a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_code_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('city_code', sa.SMALLINT(), nullable=True),
    sa.Column('rate_1m', sa.SMALLINT(), nullable=True),
    sa.Column('rate_30m', sa.SMALLINT(), nullable=True),
    sa.Column('rate_ipseg_30m', sa.SMALLINT(), nullable=True),
    sa.Column('unlock_count_1m', sa.SMALLINT(), nullable=True),
    sa.Column('unlock_count_30m', sa.SMALLINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ip_ipseg_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=12), nullable=True),
    sa.Column('ipseg', sa.CHAR(length=32), nullable=True),
    sa.Column('ipseg_status', sa.SMALLINT(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_ipseg_info_ipseg'), 'ip_ipseg_info', ['ipseg'], unique=True)
    op.create_table('ip_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=16), nullable=True),
    sa.Column('logname', sa.String(length=11), nullable=True),
    sa.Column('ip_log', sa.CHAR(length=32), nullable=True),
    sa.Column('lock_1m_times', sa.SMALLINT(), nullable=True),
    sa.Column('lock_30m_times', sa.SMALLINT(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('area_info', sa.String(length=30), nullable=True),
    sa.Column('today_times', sa.SMALLINT(), nullable=True),
    sa.Column('total_times', sa.Integer(), nullable=True),
    sa.Column('lock_status', sa.SMALLINT(), nullable=True),
    sa.Column('white_list_status', sa.CHAR(length=1), nullable=True),
    sa.Column('unlock_times', sa.Integer(), nullable=True),
    sa.Column('unlock_after_lockd', sa.SMALLINT(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('lastest_time', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['ip_code_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_info_ip_log'), 'ip_info', ['ip_log'], unique=True)
    op.create_table('ip_visit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partno', sa.String(length=30), nullable=True),
    sa.Column('query_time', sa.DateTime(), nullable=True),
    sa.Column('ip_detail_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ip_detail_id'], ['ip_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ip_visit_log')
    op.drop_index(op.f('ix_ip_info_ip_log'), table_name='ip_info')
    op.drop_table('ip_info')
    op.drop_index(op.f('ix_ip_ipseg_info_ipseg'), table_name='ip_ipseg_info')
    op.drop_table('ip_ipseg_info')
    op.drop_table('ip_code_info')
    # ### end Alembic commands ###
