"""empty message

Revision ID: 287eae101d50
Revises: 8c529ca88e77
Create Date: 2018-06-25 16:30:42.358146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '287eae101d50'
down_revision = '8c529ca88e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ip_info', 'lastest_aa')
    op.drop_column('ip_ipseg_info', 'lastest_aa_bb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_ipseg_info', sa.Column('lastest_aa_bb', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('ip_info', sa.Column('lastest_aa', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
