"""empty message

Revision ID: 291c73dfecf8
Revises: 5f589e3f6334
Create Date: 2018-06-25 16:04:14.337101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '291c73dfecf8'
down_revision = '5f589e3f6334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ip_info', 'lock_status',
               existing_type=mysql.CHAR(length=1),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ip_info', 'lock_status',
               existing_type=sa.SMALLINT(),
               type_=mysql.CHAR(length=1),
               existing_nullable=True)
    # ### end Alembic commands ###
