"""empty message

Revision ID: 40a47fc282bf
Revises: 291c73dfecf8
Create Date: 2018-06-25 16:11:45.656365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40a47fc282bf'
down_revision = '291c73dfecf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_info', sa.Column('lastest_aa', sa.Integer(), nullable=True))
    op.drop_column('ip_info', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_info', sa.Column('test', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('ip_info', 'lastest_aa')
    # ### end Alembic commands ###
