"""empty message

Revision ID: 5f589e3f6334
Revises: 1f463034105a
Create Date: 2018-06-25 16:03:50.762538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f589e3f6334'
down_revision = '1f463034105a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ip_info', 'lock_status',
               existing_type=mysql.SMALLINT(display_width=6),
               type_=sa.CHAR(length=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ip_info', 'lock_status',
               existing_type=sa.CHAR(length=1),
               type_=mysql.SMALLINT(display_width=6),
               existing_nullable=True)
    # ### end Alembic commands ###
