"""empty message

Revision ID: e9870bc374ce
Revises: faf2e62aa431
Create Date: 2018-07-03 13:20:18.014680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9870bc374ce'
down_revision = 'faf2e62aa431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_visit_log', sa.Column('lock_flag', sa.SMALLINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ip_visit_log', 'lock_flag')
    # ### end Alembic commands ###
