"""empty message

Revision ID: faf2e62aa431
Revises: 287eae101d50
Create Date: 2018-06-28 11:16:51.591097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'faf2e62aa431'
down_revision = '287eae101d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_code_info', sa.Column('lock_max_1m', sa.SMALLINT(), nullable=True))
    op.add_column('ip_code_info', sa.Column('lock_max_30m', sa.SMALLINT(), nullable=True))
    op.drop_column('ip_code_info', 'unlock_count_30m')
    op.drop_column('ip_code_info', 'unlock_count_1m')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_code_info', sa.Column('unlock_count_1m', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('ip_code_info', sa.Column('unlock_count_30m', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.drop_column('ip_code_info', 'lock_max_30m')
    op.drop_column('ip_code_info', 'lock_max_1m')
    # ### end Alembic commands ###
